import { existsSync } from 'fs';
import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from 'fs/promises';
import { dirname, isAbsolute, join, relative } from 'path';

import {
  type EnvironmentConfig,
  type EnvironmentRepositoryConfig,
  DEFAULT_SOURCE_CONTROL_PROVIDER,
  COMMAND_DEFAULT_TIMEOUT,
  PRODUCT_NAME,
  buildRepositoryCloneUrl,
  renderManualSkillMarkdown,
  stripCloneUrlUserInfo,
  type SourceControlProvider,
} from '@roomote/types';
import { sdk } from '@roomote/sdk/client';

import {
  CommandExecutor,
  ExecutionError,
  type ExecutionResult,
} from '../command-executor';
import { createWorkspaceRepositoryPreparationError } from '../commands/setup/workspace/repository-preparation';
import {
  SOURCE_CONTROL_GIT_CONFIG_PATH,
  ensureGitCredentialHelper,
  getGitHubTokenFileStatus,
  writeGitHubTokenFile,
} from '../lib/github-token';

interface PrepareRepositoryOptions {
  toolVersionsConfig?: Record<string, string>;
  setDefaultRemote?: boolean;
  sourceControlProvider?: SourceControlProvider;
}

interface ExecuteEnvironmentRepositoryCommandsOptions {
  continueOnError?: boolean;
  onCommandStart?: (event: { repository: string; commandName: string }) => void;
  onCommandResult?: (event: {
    repository: string;
    result: ExecutionResult;
  }) => void;
  onCommandFailure?: (failure: {
    repository: string;
    result: ExecutionResult;
  }) => void;
}

type WorkspaceTimingRecorder = <T>(
  label: string,
  fn: () => Promise<T> | T,
) => Promise<T>;

const SKILLS_INSTALL_COMMAND = 'npx -y skills add';
const REPOSITORY_FETCH_MAX_ATTEMPTS = 5;
const REPOSITORY_FETCH_INITIAL_RETRY_DELAY_MS = 2_000;
const RESET_LOCAL_CHANGES_COMMAND =
  'if git rev-parse --verify HEAD >/dev/null 2>&1; then git reset --hard HEAD; fi';
const REPOSITORY_WORKTREE_SYNC_TIMEOUT = COMMAND_DEFAULT_TIMEOUT;
const GENERATED_REPO_MISE_CONFIG_FILENAME = 'mise.local.toml';
const GENERATED_REPO_MISE_CONFIG_HEADER =
  '# Generated by Roomote. Repository-owned tool config wins; these entries only fill missing tools.\n';
const REPO_MISE_CONFIG_FILENAMES = [
  '.tool-versions',
  GENERATED_REPO_MISE_CONFIG_FILENAME,
  '.mise.local.toml',
  'mise.toml',
  '.mise.toml',
];

/**
 * Escape a string for safe use inside single-quoted shell arguments.
 * Replaces each `'` with `'\''` (end quote, escaped quote, re-open quote).
 */
function shellEscape(value: string): string {
  return value.replace(/'/g, "'\\''");
}

function parseOriginHeadLsRemote(stdout?: string): string | null {
  if (!stdout) {
    return null;
  }

  for (const line of stdout.split('\n')) {
    const match = line.match(/^ref:\s+refs\/heads\/([^\s]+)\s+HEAD$/);
    if (match?.[1]) {
      return match[1];
    }
  }

  return null;
}

function parseLocalOriginHead(stdout?: string): string | null {
  const ref = stdout?.trim();

  if (!ref?.startsWith('origin/')) {
    return null;
  }

  return ref.slice('origin/'.length) || null;
}

function renderToolVersionsFile(
  toolVersionsConfig: Record<string, string>,
): string {
  return Object.entries(toolVersionsConfig)
    .map(([tool, version]) => `${tool} ${version}`)
    .join('\n')
    .concat('\n');
}

function parseToolVersionsFile(content: string): Record<string, string> {
  return Object.fromEntries(
    content
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line.length > 0 && !line.startsWith('#'))
      .map((line) => {
        const [tool, ...versionParts] = line.split(/\s+/);
        return [tool, versionParts.join(' ')];
      })
      .filter(([tool, version]) => Boolean(tool) && Boolean(version)),
  );
}

function renderGeneratedRepoMiseConfig(
  toolVersionsConfig: Record<string, string>,
): string {
  const toolsBlock = Object.entries(toolVersionsConfig)
    .map(([tool, version]) => `${tool} = ${JSON.stringify(version)}`)
    .join('\n');

  return `${GENERATED_REPO_MISE_CONFIG_HEADER}\n[tools]\n${toolsBlock}\n`;
}

export class WorkspaceManager {
  constructor(
    private readonly workspaceRoot: string,
    private readonly env: NodeJS.ProcessEnv,
    private readonly verbose = false,
    private readonly recordTiming?: WorkspaceTimingRecorder,
  ) {}

  private async timed<T>(label: string, fn: () => Promise<T> | T): Promise<T> {
    return this.recordTiming ? this.recordTiming(label, fn) : await fn();
  }

  public async configure(options?: {
    gitAuthorName?: string;
    gitAuthorEmail?: string;
  }): Promise<void> {
    // Write the file-backed credential helper so git always reads the
    // freshest token, even after the periodic refresh replaces the file.
    const credentialHelperPath = ensureGitCredentialHelper();

    const gitEmail = shellEscape(
      options?.gitAuthorEmail || 'roomote@roomote.dev',
    );
    const gitName = shellEscape(options?.gitAuthorName || PRODUCT_NAME);

    const executor = new CommandExecutor(
      this.workspaceRoot,
      this.env,
      this.verbose,
    );

    await executor.executeAll([
      {
        name: 'GitHub auth setup-git',
        run: 'if [ -n "${GH_TOKEN:-}" ]; then gh auth setup-git; else echo "Skipping gh auth setup-git because GH_TOKEN is not set"; fi',
        timeout: 60,
        continue_on_error: false,
      },
      {
        // Override provider credential helpers with a file-backed helper that
        // reads the latest token from disk for each git operation.
        name: 'GitHub credential helper (file-backed)',
        run: `git config --global --replace-all credential.https://github.com.helper '!${credentialHelperPath}'`,
        timeout: 60,
        continue_on_error: false,
      },
      {
        name: 'GitLab credential helper (file-backed)',
        run: `git config --global --replace-all credential.https://gitlab.com.helper '!${credentialHelperPath}'`,
        timeout: 60,
        continue_on_error: false,
      },
      {
        name: 'GitLab credential useHttpPath',
        run: 'git config --global credential.https://gitlab.com.useHttpPath true',
        timeout: 60,
        continue_on_error: false,
      },
      {
        name: 'Source-control credential helper (file-backed)',
        run: `git config --global --replace-all credential.helper '!${credentialHelperPath}'`,
        timeout: 60,
        continue_on_error: false,
      },
      {
        name: 'Source-control credential useHttpPath',
        run: 'git config --global credential.useHttpPath true',
        timeout: 60,
        continue_on_error: false,
      },
      {
        name: 'Source-control auth include file',
        run: `git config --global --get-all include.path | grep -Fx -- '${shellEscape(
          SOURCE_CONTROL_GIT_CONFIG_PATH,
        )}' >/dev/null || git config --global --add include.path '${shellEscape(
          SOURCE_CONTROL_GIT_CONFIG_PATH,
        )}'`,
        timeout: 60,
        continue_on_error: false,
      },
      {
        name: 'Git config email',
        run: `git config --global user.email '${gitEmail}'`,
        timeout: 60,
        continue_on_error: false,
      },
      {
        name: 'Git config name',
        run: `git config --global user.name '${gitName}'`,
        timeout: 60,
        continue_on_error: false,
      },
    ]);
  }

  /**
   * Install tool versions using mise.
   *
   * Workspace-level tool versions continue to use a shared `.tool-versions`
   * file at the workspace root. Repository-level tool versions are treated as
   * fallback entries: any checked-in repo `.tool-versions` wins first, and
   * missing tools from the environment config are written into a generated
   * `mise.local.toml` so they can fill gaps without replacing repo-owned pins.
   */
  private async installToolVersions(
    targetPath: string,
    toolVersionsConfig?: Record<string, string>,
    options?: {
      excludeFromGit?: boolean;
    },
  ): Promise<void> {
    const toolVersionsPath = join(targetPath, '.tool-versions');
    const repoToolVersions = existsSync(toolVersionsPath)
      ? parseToolVersionsFile(await readFile(toolVersionsPath, 'utf-8'))
      : {};
    const repoFallbackConfig = toolVersionsConfig
      ? Object.fromEntries(
          Object.entries(toolVersionsConfig).filter(
            ([tool]) => repoToolVersions[tool] === undefined,
          ),
        )
      : undefined;
    const hasGeneratedRepoFallback = await this.syncGeneratedRepoMiseConfig(
      targetPath,
      repoFallbackConfig,
      options,
    );
    const hasRepoMiseConfig = REPO_MISE_CONFIG_FILENAMES.some((filename) =>
      existsSync(join(targetPath, filename)),
    );

    if (!hasRepoMiseConfig && !hasGeneratedRepoFallback) {
      return;
    }

    console.log(`Installing tools from repo-local mise config`);

    const executor = new CommandExecutor(targetPath, this.env, this.verbose);

    await executor.execute({
      name: 'Install tool versions',
      run: 'mise install',
      timeout: 300,
      continue_on_error: true,
    });

    const listResult = await executor.execute({
      name: 'Listing installed tools',
      run: 'mise ls --json',
      timeout: 30,
      continue_on_error: true,
    });

    if (listResult.success && listResult.stdout) {
      try {
        const tools: Record<string, { version: string; active: boolean }[]> =
          JSON.parse(listResult.stdout);

        const toolVersions = Object.entries(tools).flatMap(([name, versions]) =>
          versions.filter((v) => v.active).map((v) => `${name}@${v.version}`),
        );

        if (toolVersions.length > 0) {
          console.log(toolVersions.join(', '));
        }
      } catch {
        // Ignore errors.
      }
    }
  }

  public async installWorkspaceToolVersions(
    toolVersionsConfig?: Record<string, string>,
  ): Promise<void> {
    if (!toolVersionsConfig || Object.keys(toolVersionsConfig).length === 0) {
      return;
    }

    const toolVersionsPath = join(this.workspaceRoot, '.tool-versions');

    await writeFile(
      toolVersionsPath,
      renderToolVersionsFile(toolVersionsConfig),
      'utf-8',
    );
    console.log(`Generated shared .tool-versions from environment config`);

    const executor = new CommandExecutor(
      this.workspaceRoot,
      this.env,
      this.verbose,
    );

    await executor.execute({
      name: 'Install tool versions',
      run: 'mise install',
      timeout: 300,
      continue_on_error: true,
    });

    const listResult = await executor.execute({
      name: 'Listing installed tools',
      run: 'mise ls --json',
      timeout: 30,
      continue_on_error: true,
    });

    if (listResult.success && listResult.stdout) {
      try {
        const tools: Record<string, { version: string; active: boolean }[]> =
          JSON.parse(listResult.stdout);

        const toolVersions = Object.entries(tools).flatMap(([name, versions]) =>
          versions.filter((v) => v.active).map((v) => `${name}@${v.version}`),
        );

        if (toolVersions.length > 0) {
          console.log(toolVersions.join(', '));
        }
      } catch {
        // Ignore errors.
      }
    }
  }

  private async syncGeneratedRepoMiseConfig(
    targetPath: string,
    toolVersionsConfig?: Record<string, string>,
    options?: {
      excludeFromGit?: boolean;
    },
  ): Promise<boolean> {
    const generatedConfigPath = join(
      targetPath,
      GENERATED_REPO_MISE_CONFIG_FILENAME,
    );

    if (!toolVersionsConfig || Object.keys(toolVersionsConfig).length === 0) {
      return await this.removeGeneratedRepoMiseConfig(targetPath);
    }

    let existingContent: string | undefined;

    if (existsSync(generatedConfigPath)) {
      try {
        existingContent = await readFile(generatedConfigPath, 'utf-8');
      } catch {
        existingContent = undefined;
      }
    }

    if (
      existingContent &&
      !existingContent.startsWith(GENERATED_REPO_MISE_CONFIG_HEADER)
    ) {
      console.warn(
        `Skipping generated ${GENERATED_REPO_MISE_CONFIG_FILENAME} because the repository already defines it`,
      );
      return true;
    }

    const nextContent = renderGeneratedRepoMiseConfig(toolVersionsConfig);

    if (existingContent !== nextContent) {
      await writeFile(generatedConfigPath, nextContent, 'utf-8');
      console.log(
        `Generated ${GENERATED_REPO_MISE_CONFIG_FILENAME} from environment config fallback`,
      );
    }

    if (options?.excludeFromGit !== false) {
      await this.addToGitExclude(
        targetPath,
        GENERATED_REPO_MISE_CONFIG_FILENAME,
      );
    }

    await this.trustGeneratedRepoMiseConfig(targetPath);

    return true;
  }

  private async removeGeneratedRepoMiseConfig(
    targetPath: string,
  ): Promise<boolean> {
    const generatedConfigPath = join(
      targetPath,
      GENERATED_REPO_MISE_CONFIG_FILENAME,
    );

    if (!existsSync(generatedConfigPath)) {
      return false;
    }

    try {
      const existingContent = await readFile(generatedConfigPath, 'utf-8');

      if (!existingContent.startsWith(GENERATED_REPO_MISE_CONFIG_HEADER)) {
        return true;
      }
    } catch {
      return true;
    }

    await rm(generatedConfigPath, { force: true });
    console.log(`Removed generated ${GENERATED_REPO_MISE_CONFIG_FILENAME}`);

    return false;
  }

  private async trustGeneratedRepoMiseConfig(
    targetPath: string,
  ): Promise<void> {
    const executor = new CommandExecutor(targetPath, this.env, this.verbose);

    await executor.execute({
      name: 'Trust generated mise config',
      run: `mise trust '${GENERATED_REPO_MISE_CONFIG_FILENAME}'`,
      timeout: 30,
      continue_on_error: true,
    });
  }

  /**
   * Append a pattern to `.git/info/exclude` if it isn't already listed.
   * This is a per-clone gitignore that is NOT tracked by git.
   */
  private async addToGitExclude(
    repoPath: string,
    pattern: string,
  ): Promise<void> {
    const excludePath = join(repoPath, '.git', 'info', 'exclude');

    // Ensure the directory exists (it should, but be safe).
    await mkdir(join(repoPath, '.git', 'info'), { recursive: true });

    let existing = '';

    try {
      existing = await readFile(excludePath, 'utf-8');
    } catch {
      // File may not exist yet.
    }

    const lines = existing.split('\n');

    if (!lines.includes(pattern)) {
      const separator = existing.endsWith('\n') || existing === '' ? '' : '\n';
      await writeFile(
        excludePath,
        `${existing}${separator}${pattern}\n`,
        'utf-8',
      );
    }
  }

  private async sleep(ms: number): Promise<void> {
    await new Promise((resolve) => setTimeout(resolve, ms));
  }

  private async markGitSafeDirectory(targetPath: string): Promise<void> {
    const safePath = shellEscape(targetPath);

    const executor = new CommandExecutor(
      this.workspaceRoot,
      this.env,
      this.verbose,
    );

    await executor.execute({
      name: 'Git safe directory',
      run: `git config --global --get-all safe.directory | grep -Fx -- '${safePath}' >/dev/null || git config --global --add safe.directory '${safePath}'`,
      timeout: 60,
      continue_on_error: true,
    });
  }

  /**
   * Resolve a repository-relative path and reject any value that escapes
   * the workspace root. Repository full names are provider-synced and reach
   * both shell commands and recursive deletes, so traversal segments (`..`)
   * from a hostile or misconfigured source-control origin must never
   * resolve outside the workspace.
   */
  private resolveContainedWorkspacePath(relativePath: string): string {
    const targetPath = join(this.workspaceRoot, relativePath);
    const relativeToRoot = relative(this.workspaceRoot, targetPath);

    if (
      relativeToRoot === '' ||
      relativeToRoot.startsWith('..') ||
      isAbsolute(relativeToRoot)
    ) {
      throw new Error(
        `Repository path '${relativePath}' resolves outside the workspace root and was rejected.`,
      );
    }

    return targetPath;
  }

  /**
   * GitHub task runs always receive a GitHub App installation token at
   * dequeue, which the worker writes to the file-backed git credential
   * helper before repository setup. If no credential signal is present
   * here, git would fall back to slow anonymous clone retries and fail
   * checkout with a cryptic error — fail fast with an operator-actionable
   * message instead. Logs presence signals only, never token material.
   */
  private ensureGitHubCredentialsAvailable(repoFullName: string): void {
    const tokenFile = getGitHubTokenFileStatus();
    const envToken = this.env.GH_TOKEN?.trim() || this.env.GITHUB_TOKEN?.trim();

    console.log(
      `GitHub credential check for ${repoFullName}: tokenFilePresent=${tokenFile.present} tokenFileNonEmpty=${tokenFile.nonEmpty} envTokenPresent=${Boolean(envToken)}`,
    );

    if (tokenFile.nonEmpty) {
      return;
    }

    if (envToken) {
      // The git credential helper and gh wrapper only read the token file;
      // a token that exists solely as an env var would never reach git and
      // the clone would still run anonymously.
      console.log(
        'GitHub token file is empty; writing the GH_TOKEN/GITHUB_TOKEN env var to the token file for git authentication.',
      );
      writeGitHubTokenFile(envToken);
      return;
    }

    throw new Error(
      `No GitHub credentials are available for ${repoFullName}: the worker's token file (~/.roomote/gh-token) is missing or empty and no GH_TOKEN/GITHUB_TOKEN env var is set. ` +
        'The control plane creates a GitHub App installation token when the run is dequeued; verify the GitHub App is installed for the repository owner, the installation covers this repository, and repositories are synced. ' +
        'Anonymous git access is rate limited and fails for private repositories, so repository setup was stopped before cloning.',
    );
  }

  public async prepareRepository(
    repoFullName: string,
    branch: string | undefined,
    sha: string | undefined,
    preserveGitState = false,
    cleanupLegacyPaths = false,
    options: PrepareRepositoryOptions = {},
  ): Promise<string> {
    const sourceControlProvider =
      options.sourceControlProvider ?? DEFAULT_SOURCE_CONTROL_PROVIDER;
    const repo = await this.timed(
      `prepare ${repoFullName}: resolve repository`,
      () =>
        sdk.repositories.findRepository({
          fullName: repoFullName,
          sourceControlProvider,
        }),
    );

    if (
      !repo &&
      (sourceControlProvider === 'github' ||
        sourceControlProvider === 'gitea' ||
        sourceControlProvider === 'ado')
    ) {
      throw new Error(`Repository not found: ${repoFullName}`);
    }

    const { fullName, defaultBranch } = repo ?? {
      fullName: repoFullName,
      defaultBranch: branch || 'main',
    };
    // Stored clone URLs may embed userinfo (e.g. Azure DevOps rows synced
    // before URLs were normalized), which would bypass the credential
    // proxy's insteadOf prefix rewrite — always clone without it.
    const cloneUrl = stripCloneUrlUserInfo(
      repo?.cloneUrl ??
        buildRepositoryCloneUrl({
          provider: sourceControlProvider,
          repositoryFullName: fullName,
        }),
    );
    const targetBranch = branch || defaultBranch;

    console.log(`Preparing ${fullName}#${targetBranch}`);

    const repoPath = this.resolveContainedWorkspacePath(fullName);
    const legacyRepoPath = this.resolveContainedWorkspacePath(
      fullName.split('/').pop() ?? fullName,
    );
    let resolvedRepoPath =
      preserveGitState &&
      repoPath !== legacyRepoPath &&
      !existsSync(repoPath) &&
      existsSync(legacyRepoPath)
        ? legacyRepoPath
        : repoPath;

    // An interrupted earlier run can leave a directory behind that is not a
    // git repository (e.g. a clone killed before .git was written). Treating
    // it as an existing clone would skip cloning here and fail much later at
    // checkout with a cryptic "'origin/<branch>' is not a commit" error.
    if (
      existsSync(resolvedRepoPath) &&
      !existsSync(join(resolvedRepoPath, '.git'))
    ) {
      console.warn(
        `Repository path ${resolvedRepoPath} exists but is not a git repository; removing it and cloning again.`,
      );
      await rm(resolvedRepoPath, { recursive: true, force: true });
      resolvedRepoPath = repoPath;
    }

    const needsClone = !existsSync(resolvedRepoPath);

    if (
      sourceControlProvider === 'github' &&
      (needsClone || !preserveGitState)
    ) {
      this.ensureGitHubCredentialsAvailable(fullName);
    }

    if (!needsClone) {
      console.log(`Repository ${fullName} already exists, skipping clone`);
    } else {
      console.log(`Cloning ${fullName}`);
      const executor = new CommandExecutor(
        this.workspaceRoot,
        this.env,
        this.verbose,
      );

      await mkdir(dirname(resolvedRepoPath), { recursive: true });

      await this.timed(`prepare ${fullName}: clone`, () =>
        executor.execute({
          name: 'Git clone',
          // Use git transport directly so clone works with the worker's
          // file-backed credential helper and avoids gh's extra API lookup.
          // Escape both args: cloneUrl is provider-synced and may include
          // shell metacharacters from a hostile self-hosted origin.
          // Retries re-run this same line, and a clone killed mid-transfer
          // (e.g. by the timeout) leaves a partial target directory that
          // would make every retry fail with "destination path already
          // exists" — remove it first. Safe: needsClone guarantees the path
          // did not exist before the first attempt.
          // Blobless partial clone: full commit/tree history (so log,
          // merge-base, and PR base computations work), but historical
          // blobs are fetched lazily instead of up front — large repos
          // clone in a fraction of the time. Lazy fetches go through the
          // same credential proxy that is alive for the whole run.
          run: `rm -rf -- '${shellEscape(fullName)}' && git clone --filter=blob:none '${shellEscape(cloneUrl)}' '${shellEscape(fullName)}'`,
          // Allow brief auth and repository visibility propagation delays.
          retries: 4,
          timeout: 300,
          continue_on_error: false,
        }),
      );
    }

    let stats;

    try {
      stats = await stat(resolvedRepoPath);
    } catch (_error) {
      throw new Error(`Path '${resolvedRepoPath}' does not exist`);
    }

    if (!stats.isDirectory()) {
      throw new Error(`Path '${resolvedRepoPath}' is not a directory`);
    }

    const legacyPathToRepoPath = relative(legacyRepoPath, repoPath);
    const legacyRepoPathContainsCanonicalPath =
      legacyPathToRepoPath === '' ||
      (!legacyPathToRepoPath.startsWith('..') &&
        !isAbsolute(legacyPathToRepoPath));

    if (
      cleanupLegacyPaths &&
      !preserveGitState &&
      legacyRepoPath !== repoPath &&
      !legacyRepoPathContainsCanonicalPath &&
      existsSync(legacyRepoPath)
    ) {
      await rm(legacyRepoPath, { recursive: true, force: true });
      console.log(`Removed legacy repo path: ${legacyRepoPath}`);
    }

    await this.timed(`prepare ${fullName}: mark git safe directory`, () =>
      this.markGitSafeDirectory(resolvedRepoPath),
    );

    const executor = new CommandExecutor(
      resolvedRepoPath,
      this.env,
      this.verbose,
    );

    if (!preserveGitState) {
      const usesStoredDefaultBranch = branch === undefined || branch === '';

      await this.syncRepositoryGitState({
        executor,
        repoFullName: fullName,
        targetBranch,
        sha,
        repositoryId: repo?.id,
        allowRemoteHeadFallback: usesStoredDefaultBranch,
        setDefaultRemote:
          sourceControlProvider === 'github' &&
          (options.setDefaultRemote ?? true),
      });
    }

    // Install tool versions if .tool-versions exists.
    await this.timed(`prepare ${fullName}: install tool versions`, () =>
      this.installToolVersions(resolvedRepoPath, options.toolVersionsConfig),
    );

    return resolvedRepoPath;
  }

  public async prepareEnvironmentRepositories(
    environmentConfig: EnvironmentConfig,
    preserveGitState = false,
    cleanupLegacyPaths = false,
    sourcePin?: {
      sourceRepo?: string;
      sourceBranch?: string;
      sourceSha?: string;
    },
    options: Pick<PrepareRepositoryOptions, 'sourceControlProvider'> = {},
  ): Promise<{
    repoPaths: Record<string, string>;
  }> {
    console.log(
      `Preparing repositories for "${environmentConfig.name}" environment`,
    );
    const repoPaths: Record<string, string> = {};

    const preparationResults = await Promise.allSettled(
      environmentConfig.repositories.map(async (repoConfig) => {
        const isSourceRepo = sourcePin?.sourceRepo === repoConfig.repository;

        const pinnedBranch = isSourceRepo
          ? sourcePin?.sourceBranch === ''
            ? (repoConfig.branch ?? '')
            : (sourcePin?.sourceBranch ?? repoConfig.branch)
          : repoConfig.branch;

        const pinnedSha = isSourceRepo ? sourcePin?.sourceSha : undefined;

        const repoPath = await this.prepareRepository(
          repoConfig.repository,
          pinnedBranch,
          pinnedSha,
          preserveGitState,
          cleanupLegacyPaths,
          {
            sourceControlProvider: options.sourceControlProvider,
            toolVersionsConfig: repoConfig.tool_versions,
            setDefaultRemote: false,
          },
        );

        const repoName = repoConfig.repository;

        repoPaths[repoName] = repoPath;
      }),
    );

    const failedPreparations = preparationResults
      .map((result, index) => ({
        result,
        repoConfig: environmentConfig.repositories[index],
      }))
      .filter(
        (
          item,
        ): item is {
          result: PromiseRejectedResult;
          repoConfig: EnvironmentRepositoryConfig | undefined;
        } => item.result.status === 'rejected',
      );

    if (failedPreparations.length > 0) {
      throw createWorkspaceRepositoryPreparationError({
        workspaceType: 'environment',
        totalRepositories: environmentConfig.repositories.length,
        preparedRepositoryCount:
          environmentConfig.repositories.length - failedPreparations.length,
        failures: failedPreparations.map(({ result, repoConfig }) => ({
          repository:
            repoConfig?.repository ?? 'unknown environment repository',
          error: result.reason,
        })),
      });
    }

    console.log(
      `Successfully prepared repositories for "${environmentConfig.name}" environment`,
    );

    return {
      repoPaths,
    };
  }

  private async syncRepositoryGitState({
    executor,
    repoFullName,
    targetBranch,
    sha,
    repositoryId,
    allowRemoteHeadFallback,
    setDefaultRemote,
  }: {
    executor: CommandExecutor;
    repoFullName: string;
    targetBranch: string;
    sha?: string;
    repositoryId?: string;
    allowRemoteHeadFallback: boolean;
    setDefaultRemote: boolean;
  }): Promise<void> {
    await this.timed(`prepare ${repoFullName}: git fetch`, () =>
      this.fetchRepositoryWithRetry({
        executor,
        repoFullName,
      }),
    );

    let checkoutBranch: string;

    try {
      checkoutBranch = await this.resolveCheckoutBranch({
        executor,
        repoFullName,
        targetBranch,
        allowRemoteHeadFallback,
      });
    } catch (error) {
      // A branch that cannot be resolved is usually a real error, but a
      // brand-new repository legitimately has no branches yet (for example
      // one just created through github.com/new without a README). Only that
      // confirmed-empty case is handled specially; anything else rethrows.
      if (await this.remoteHasNoBranches(executor)) {
        await this.prepareEmptyRepositoryWorktree({
          executor,
          repoFullName,
          targetBranch,
          sha,
          setDefaultRemote,
        });
        return;
      }

      throw error;
    }

    if (
      allowRemoteHeadFallback &&
      repositoryId &&
      checkoutBranch !== targetBranch
    ) {
      // The task used stored default-branch metadata and origin/HEAD
      // disagreed with it, so the stored row is stale. Report the resolved
      // branch so the control plane self-heals; never block or fail the
      // task on this.
      this.reportResolvedDefaultBranch({
        repositoryId,
        repoFullName,
        defaultBranch: checkoutBranch,
      });
    }

    const remoteBranchRef = `origin/${checkoutBranch}`;

    await this.timed(`prepare ${repoFullName}: git checkout/reset`, () =>
      executor.executeAll([
        {
          // Large repositories can legitimately take minutes to rewrite
          // the worktree while still making progress, so keep these
          // local sync steps on the environment command timeout instead
          // of the shorter one-minute helper default.
          // Reset any local changes before checkout to prevent conflicts.
          name: 'Git reset local changes',
          run: RESET_LOCAL_CHANGES_COMMAND,
          timeout: REPOSITORY_WORKTREE_SYNC_TIMEOUT,
          continue_on_error: false,
        },
        {
          // Clean untracked files and directories before checkout to prevent conflicts.
          name: 'Git clean untracked',
          run: 'git clean -fd',
          timeout: REPOSITORY_WORKTREE_SYNC_TIMEOUT,
          continue_on_error: false,
        },
        {
          // Use -B flag to create branch if it doesn't exist, or reset it if it does.
          // Quote/escape all interpolated refs: branch names are
          // attacker-controlled via webhooks and launch APIs and reach bash.
          name: 'Git checkout branch',
          run: `git checkout -B '${shellEscape(checkoutBranch)}' '${shellEscape(remoteBranchRef)}'`,
          timeout: REPOSITORY_WORKTREE_SYNC_TIMEOUT,
          continue_on_error: false,
        },
        {
          // Final reset to ensure exact match with remote (redundant but safe).
          name: 'Git reset to remote',
          run: `git reset --hard '${shellEscape(remoteBranchRef)}'`,
          timeout: REPOSITORY_WORKTREE_SYNC_TIMEOUT,
          continue_on_error: false,
        },
        ...(sha
          ? [
              {
                name: 'Git pin to sha',
                run: `git reset --hard '${shellEscape(sha)}'`,
                timeout: REPOSITORY_WORKTREE_SYNC_TIMEOUT,
                continue_on_error: false,
              },
            ]
          : []),
        ...(setDefaultRemote
          ? [
              {
                name: 'Set default remote repo.',
                run: `gh repo set-default '${shellEscape(repoFullName)}'`,
                timeout: 60,
                continue_on_error: true,
              },
            ]
          : []),
      ]),
    );
  }

  /**
   * A brand-new repository can have no branches at all (for example one just
   * created through github.com/new without a README). An errorless
   * `git ls-remote --heads` with no output is the ground truth for that
   * state; a failed lookup is treated as non-empty so real errors surface
   * through the normal checkout path.
   */
  private async remoteHasNoBranches(
    executor: CommandExecutor,
  ): Promise<boolean> {
    const result = await executor.execute({
      name: 'Git check remote branches',
      run: 'git ls-remote --heads origin',
      timeout: 60,
      retries: 1,
      continue_on_error: true,
    });

    return result.success && (result.stdout ?? '').trim() === '';
  }

  /**
   * Prepare a worktree for a repository whose remote has no commits. The
   * checkout/reset command block requires `origin/<branch>` refs that do not
   * exist yet, so it is skipped entirely; the unborn local branch is instead
   * pointed at the stored default branch (GitHub reports `default_branch`
   * even for empty repositories) so the first commit lands where the remote
   * expects it. Local commits are preserved: a reused workspace mid-bootstrap
   * may hold work that has not been pushed yet.
   */
  private async prepareEmptyRepositoryWorktree({
    executor,
    repoFullName,
    targetBranch,
    sha,
    setDefaultRemote,
  }: {
    executor: CommandExecutor;
    repoFullName: string;
    targetBranch: string;
    sha?: string;
    setDefaultRemote: boolean;
  }): Promise<void> {
    if (sha) {
      throw new Error(
        `Cannot pin ${repoFullName} to ${sha}: the remote repository has no commits.`,
      );
    }

    const localHead = await executor.execute({
      name: 'Git check local commits',
      run: 'git rev-parse --verify --quiet HEAD',
      timeout: 60,
      continue_on_error: true,
    });

    if (!localHead.success) {
      await executor.execute({
        name: 'Git point unborn HEAD at default branch',
        run: `git symbolic-ref HEAD 'refs/heads/${shellEscape(targetBranch)}'`,
        timeout: 60,
        continue_on_error: false,
      });
    }

    if (setDefaultRemote) {
      await executor.execute({
        name: 'Set default remote repo.',
        run: `gh repo set-default '${shellEscape(repoFullName)}'`,
        timeout: 60,
        continue_on_error: true,
      });
    }

    console.log(
      `Remote for ${repoFullName} has no commits yet; prepared an empty-repository worktree on branch ${targetBranch}.`,
    );
  }

  private async resolveCheckoutBranch({
    executor,
    repoFullName,
    targetBranch,
    allowRemoteHeadFallback,
  }: {
    executor: CommandExecutor;
    repoFullName: string;
    targetBranch: string;
    allowRemoteHeadFallback: boolean;
  }): Promise<string> {
    if (!allowRemoteHeadFallback) {
      return targetBranch;
    }

    const originHeadBranch = await this.resolveOriginHeadBranch(executor);

    if (originHeadBranch && originHeadBranch !== targetBranch) {
      console.warn(
        `Resolved origin/HEAD for ${repoFullName} to ${originHeadBranch}; ignoring stale default branch ${targetBranch}.`,
      );
      return originHeadBranch;
    }

    if (
      originHeadBranch ||
      (await this.remoteTrackingBranchExists(executor, targetBranch))
    ) {
      return originHeadBranch ?? targetBranch;
    }

    throw new Error(
      `Could not determine the default branch for ${repoFullName}: origin/HEAD was unavailable and stored branch origin/${targetBranch} does not exist.`,
    );
  }

  private reportResolvedDefaultBranch({
    repositoryId,
    repoFullName,
    defaultBranch,
  }: {
    repositoryId: string;
    repoFullName: string;
    defaultBranch: string;
  }): void {
    sdk.repositories
      .reportDefaultBranch({
        repositoryId,
        defaultBranch,
      })
      .then(
        ({ updatedCount }) => {
          if (updatedCount > 0) {
            console.log(
              `Updated stored default branch for ${repoFullName} to ${defaultBranch}.`,
            );
          }
        },
        (error: unknown) => {
          console.warn(
            `Failed to report resolved default branch for ${repoFullName}: ${
              error instanceof Error ? error.message : String(error)
            }`,
          );
        },
      );
  }

  /**
   * `git fetch` never rewrites the clone-time origin/HEAD symbolic ref, so a
   * reused workspace could keep trusting a default branch the remote moved
   * away from while the old branch still exists. Refresh the ref first; a
   * refreshed local ref is authoritative. When the refresh fails (offline,
   * rate-limited), fall back to the remote HEAD lookup before accepting the
   * possibly-stale cached ref, which is still verified against the
   * remote-tracking refs as a last resort.
   */
  private async resolveOriginHeadBranch(
    executor: CommandExecutor,
  ): Promise<string | null> {
    const refreshResult = await executor.execute({
      name: 'Git refresh origin/HEAD',
      run: 'git remote set-head origin --auto',
      timeout: 60,
      continue_on_error: true,
    });

    const localBranch = await this.resolveLocalOriginHeadBranch(executor);

    if (refreshResult.success && localBranch) {
      return localBranch;
    }

    return (await this.resolveRemoteOriginHeadBranch(executor)) ?? localBranch;
  }

  private async resolveLocalOriginHeadBranch(
    executor: CommandExecutor,
  ): Promise<string | null> {
    const symbolicRefResult = await executor.execute({
      name: 'Git resolve local origin/HEAD',
      run: 'git symbolic-ref --quiet --short refs/remotes/origin/HEAD',
      timeout: 60,
      continue_on_error: true,
    });
    const branch = parseLocalOriginHead(symbolicRefResult.stdout);

    if (!branch) {
      return null;
    }

    return (await this.remoteTrackingBranchExists(executor, branch))
      ? branch
      : null;
  }

  private async resolveRemoteOriginHeadBranch(
    executor: CommandExecutor,
  ): Promise<string | null> {
    const lsRemoteResult = await executor.execute({
      name: 'Git resolve remote HEAD',
      run: 'git ls-remote --symref origin HEAD',
      timeout: 60,
      retries: 1,
      continue_on_error: true,
    });

    const branch = parseOriginHeadLsRemote(lsRemoteResult.stdout);

    if (!branch) {
      return null;
    }

    return (await this.remoteTrackingBranchExists(executor, branch))
      ? branch
      : null;
  }

  private async remoteTrackingBranchExists(
    executor: CommandExecutor,
    branch: string,
  ): Promise<boolean> {
    const result = await executor.execute({
      name: 'Git verify remote branch',
      run: `git show-ref --verify --quiet 'refs/remotes/origin/${shellEscape(branch)}'`,
      timeout: 60,
      continue_on_error: true,
    });

    return result.success;
  }

  private async fetchRepositoryWithRetry({
    executor,
    repoFullName,
  }: {
    executor: CommandExecutor;
    repoFullName: string;
  }): Promise<void> {
    const fetchCommand = {
      name: 'Git fetch',
      run: 'git fetch --all --tags --prune --force',
      timeout: 300,
      continue_on_error: false,
    } as const;

    for (
      let attempt = 1;
      attempt <= REPOSITORY_FETCH_MAX_ATTEMPTS;
      attempt += 1
    ) {
      try {
        await executor.execute(fetchCommand);
        return;
      } catch (error) {
        if (
          !(error instanceof ExecutionError) ||
          attempt === REPOSITORY_FETCH_MAX_ATTEMPTS
        ) {
          throw error;
        }

        const delayMs =
          REPOSITORY_FETCH_INITIAL_RETRY_DELAY_MS * 2 ** (attempt - 1);
        const failureReason =
          error.result.stderr?.trim() || error.result.error || error.message;
        const isRepositoryNotFound =
          error.result.exitCode === 128 &&
          /repository not found/i.test(error.result.stderr ?? '');
        const retryReason = isRepositoryNotFound
          ? `${failureReason}. Likely a GitHub App token propagation delay rather than a missing repository`
          : failureReason;

        console.warn(
          `[WorkspaceManager] Git fetch attempt ${attempt}/${REPOSITORY_FETCH_MAX_ATTEMPTS} failed for ${repoFullName}: ${retryReason}. Retrying in ${delayMs}ms...`,
        );

        await this.sleep(delayMs);
      }
    }
  }

  public async executeEnvironmentRepositoryCommands(
    repositories: EnvironmentRepositoryConfig[],
    repoPaths: Record<string, string>,
    userEnvVars?: Record<string, string>,
    options: ExecuteEnvironmentRepositoryCommandsOptions = {},
  ): Promise<void> {
    for (const repoConfig of repositories) {
      if (!repoConfig.commands || repoConfig.commands.length === 0) {
        continue;
      }

      const repoName = repoConfig.repository;

      const repoPath = repoPaths[repoName];

      if (!repoPath) {
        throw new Error(
          `Repository path missing for command execution: ${repoConfig.repository}`,
        );
      }

      // Merge the base env with user-specified environment variables from the
      // database. User env vars take priority so they can override defaults.
      const env = userEnvVars ? { ...this.env, ...userEnvVars } : this.env;

      const userCommandExecutor = new CommandExecutor(
        repoPath,
        env,
        this.verbose,
        { detachedProcessManager: 'pm2' },
      );

      const startTimes = new Map<string, number>();
      await userCommandExecutor.executeAll(repoConfig.commands, {
        onStart: (command) => {
          startTimes.set(command.name, Date.now());
          options.onCommandStart?.({
            repository: repoConfig.repository,
            commandName: command.name,
          });
        },
        onResult: (result) => {
          const { success, command, error } = result;

          options.onCommandResult?.({
            repository: repoConfig.repository,
            result,
          });

          if (success) {
            if (startTimes && startTimes.has(command.name)) {
              const duration = Date.now() - startTimes.get(command.name)!;

              console.log(
                `[${repoConfig.repository}] ${command.name} (${duration}ms)`,
              );
            }
          } else {
            console.log(
              `[${repoConfig.repository}] ${command.name} failed -> ${error}`,
            );
            options.onCommandFailure?.({
              repository: repoConfig.repository,
              result,
            });
          }
        },
        continueOnExecutionError: options.continueOnError,
      });
    }
  }

  public async installEnvironmentSkills(
    skillsBySource: NonNullable<EnvironmentConfig['skills']>,
  ): Promise<void> {
    const commands = Object.entries(skillsBySource)
      .map(([source, skillSelection]) => {
        const normalizedSource = source.trim();

        if (!normalizedSource) {
          return undefined;
        }

        if (skillSelection === 'all') {
          return {
            name: `Install skills from ${normalizedSource}`,
            run: `${SKILLS_INSTALL_COMMAND} '${shellEscape(normalizedSource)}' -g -y`,
            timeout: COMMAND_DEFAULT_TIMEOUT,
            continue_on_error: true,
          };
        }

        const uniqueSkills = [
          ...new Set(skillSelection.map((skill) => skill.trim())),
        ].filter((skill) => skill.length > 0);

        if (uniqueSkills.length === 0) {
          return undefined;
        }

        return {
          name: `Install skills from ${normalizedSource}`,
          run: `${SKILLS_INSTALL_COMMAND} '${shellEscape(normalizedSource)}' ${uniqueSkills
            .map((skill) => `--skill '${shellEscape(skill)}'`)
            .join(' ')} -g -y`,
          timeout: COMMAND_DEFAULT_TIMEOUT,
          continue_on_error: true,
        };
      })
      .filter((command): command is NonNullable<typeof command> => !!command);

    if (commands.length === 0) {
      return;
    }

    const executor = new CommandExecutor(
      this.workspaceRoot,
      this.env,
      this.verbose,
    );

    await executor.executeAll(commands, {
      onStart: (command) => console.log(`[skills] ${command.name}`),
      onResult: ({ success, command, error }) => {
        if (!success) {
          console.log(`[skills] ${command.name} failed -> ${error}`);
        }
      },
    });
  }

  public async installManualEnvironmentSkills(
    manualSkills: NonNullable<EnvironmentConfig['manualSkills']>,
  ): Promise<void> {
    const entries = manualSkills.filter(
      (manualSkill) =>
        manualSkill.name.trim().length > 0 &&
        manualSkill.content.trim().length > 0,
    );

    if (entries.length === 0) {
      return;
    }

    const packageDir = await mkdtemp(
      join(this.workspaceRoot, '.roomote-manual-skills-'),
    );

    try {
      for (const manualSkill of entries) {
        const skillDir = join(packageDir, manualSkill.name.trim());
        await mkdir(skillDir, { recursive: true });
        await writeFile(
          join(skillDir, 'SKILL.md'),
          renderManualSkillMarkdown(manualSkill),
          'utf-8',
        );
      }

      const executor = new CommandExecutor(
        this.workspaceRoot,
        this.env,
        this.verbose,
      );

      await executor.execute({
        name: 'Install manual skills',
        run: `${SKILLS_INSTALL_COMMAND} '${shellEscape(packageDir)}' -g --all --copy`,
        timeout: COMMAND_DEFAULT_TIMEOUT,
        continue_on_error: true,
      });
    } finally {
      await rm(packageDir, { recursive: true, force: true });
    }
  }
}
